name: Continuous Integration
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - "8.0"
          - "8.1"
        dependencies:
          - "lowest"
          - "highest"
    steps:
      # Dependencies
      - uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php }}"
          extensions: yaml
      - name: Install Composer
        run: curl -sS https://getcomposer.org/installer | php
      - name: Check directory
        run: ls ./
      - name: Install Composer dependencies
        run: php composer.phar install --no-dev --prefer-dist --no-interaction
      # PHPStan
      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyze
      # PHPUnit
      - name: Run PHPUnit
        run: /vendor/bin/phpunit --bootstrap vendor/autoload.php --configuration tests/phpunit.xml