on: [push]
jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5
      - name: PHPStan (php-actions)
        uses: php-actions/phpstan@v3.0.0
        with:
          path: src/